import os
import sys

from sqlalchemy import text


# Add backend directory to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import create_app
from database.db import db


def get_columns(table_name):
    query = text(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = :table_name
        ORDER BY ordinal_position
        """
    )
    return {row[0] for row in db.session.execute(query, {"table_name": table_name}).fetchall()}


def has_table(table_name):
    query = text(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = :table_name
        """
    )
    return db.session.execute(query, {"table_name": table_name}).fetchone() is not None


def ensure_users_schema():
    if not has_table("users"):
        return

    print("Checking for legacy columns in 'users' table...")
    columns = get_columns("users")

    # Older local databases used user_id instead of id.
    if "id" not in columns and "user_id" in columns:
        print("Renaming users.user_id -> users.id ...")
        db.session.execute(text("ALTER TABLE users RENAME COLUMN user_id TO id"))
        db.session.commit()
        columns = get_columns("users")
        print("Renamed successfully.")

    if "id" not in columns:
        print("Adding missing users.id column ...")
        db.session.execute(text("ALTER TABLE users ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY"))
        db.session.commit()

        pk_query = text(
            """
            SELECT 1
            FROM information_schema.table_constraints
            WHERE table_schema = 'public'
              AND table_name = 'users'
              AND constraint_type = 'PRIMARY KEY'
            """
        )
        has_pk = db.session.execute(pk_query).fetchone() is not None
        if not has_pk:
            db.session.execute(text("ALTER TABLE users ADD PRIMARY KEY (id)"))
            db.session.commit()
        columns = get_columns("users")
        print("Added users.id.")

    if "phone_number" not in columns:
        print("Adding missing users.phone_number column ...")
        db.session.execute(text("ALTER TABLE users ADD COLUMN phone_number VARCHAR(15)"))
        db.session.commit()

    if "created_at" not in columns:
        print("Adding missing users.created_at column ...")
        db.session.execute(
            text(
                """
                ALTER TABLE users
                ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                """
            )
        )
        db.session.commit()


def ensure_participants_schema():
    if not has_table("participants"):
        return

    print("Checking for missing columns in 'participants' table...")
    columns = get_columns("participants")

    if "qualified_round" not in columns:
        print("Adding 'qualified_round' column to 'participants' table...")
        db.session.execute(text("ALTER TABLE participants ADD COLUMN qualified_round INTEGER NOT NULL DEFAULT 1"))
        db.session.commit()
        print("Successfully added 'qualified_round' column.")
    else:
        print("'qualified_round' column already exists.")

    if "registration_id" not in columns:
        print("Adding 'registration_id' column to 'participants' table...")
        db.session.execute(text("ALTER TABLE participants ADD COLUMN registration_id VARCHAR(64) UNIQUE"))
        db.session.commit()
        print("Successfully added 'registration_id' column.")
    else:
        print("'registration_id' column already exists.")


def fix_database():
    app = create_app()
    with app.app_context():
        try:
            ensure_users_schema()

            # Create any tables that don't exist after the legacy schema fix.
            import models  # noqa: F401

            db.create_all()
            print("Ensured all tables are created.")

            ensure_participants_schema()
            print("Database repair completed.")
        except Exception as e:
            db.session.rollback()
            print(f"Error fixing database: {str(e)}")
            raise


if __name__ == "__main__":
    fix_database()
